Repository upb-uc4/hlf-network, pull requests merged in 2020-11, with the labels that each got.

#92 Feature/local usage
  .gitignore
  README.md
  assets/connection_profile_kubernetes_template.yaml
  assets/kind-1.yaml
  assets/kind-2.yaml
  assets/kind.yaml
  deploy.sh
  restart.sh
  scripts/startNetwork.sh
  scripts/startNetwork/setupLocalNodeIP.sh
  scripts/util.sh
Labels: Hyperledger, enhancement

#97 Feature/lagom local testing support
  CHANGELOG.md
  restart.sh
  scripts/startNetwork.sh
  scripts/startNetwork/setupPeers.sh
Labels: Hyperledger, bug, enhancement

#100 update files to match new project structure
  deploy.sh
  k8s/org1/cli-org1.yaml
  k8s/org2/cli-org2.yaml
  restart.sh
  scripts/installChaincode.sh
  scripts/installChaincode/approveChaincodeOrg1.sh
  scripts/installChaincode/approveChaincodeOrg2.sh
  scripts/installChaincode/checkCommitReadiness.sh
  scripts/installChaincode/commitChaincode.sh
  scripts/installChaincode/packageChaincode.sh
Labels: Hyperledger, help wanted

#104 Feature/improve test output
  deploy.sh
  scripts/startNetwork/generateSecrets.sh
Labels: Hyperledger, documentation

#106 Feature/read chaincode version from jar
  CHANGELOG.md
  scripts/installChaincode.sh
  scripts/installChaincode/approveChaincodeOrg1.sh
  scripts/installChaincode/approveChaincodeOrg2.sh
  scripts/installChaincode/checkCommitReadiness.sh
  scripts/installChaincode/commitChaincode.sh
  scripts/installChaincode/installChaincodeOrg1.sh
  scripts/installChaincode/installChaincodeOrg2.sh
  scripts/installChaincode/packageChaincode.sh
Labels: Hyperledger

#105 Update readme.
  README.md
Labels: documentation
